### ISSUE TITLE
Feature request: ign tool support for introspecting plugin libraries

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-plugin#2]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-plugin/issues/2)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
# Summary

It would be cool if we could add an `ign` command file that would enable introspection of a library file by listing the plugins and interfaces present in that library file.

~~~
ign plugin --info libPlugin.so
~~~

# Motivation

It makes it more convenient for downstream users to inspect the interfaces provided by a given plugin library.

# Describe alternatives you've considered

We could write a c++ executable instead of an `ign` tool command.

# Additional context

None.

**Comment by scpeters** [comment]
this was added in #32
