### ISSUE TITLE
Provide Name accessor for Plugin class

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-plugin#5]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-plugin/issues/5)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
Migrated from https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/issues/32/provide-name-accessor-for-plugin-class (ignitionrobotics/ign-common#32)

The name of a plugin is stored within the [Info struct](https://github.com/ignitionrobotics/ign-plugin/blob/94482af3e9b2cc1cbb7c2dbeb2c7846f8283f0f6/core/include/ignition/plugin/Info.hh#L51:58), but the [Plugin class](https://github.com/ignitionrobotics/ign-plugin/blob/94482af3e9b2cc1cbb7c2dbeb2c7846f8283f0f6/core/include/ignition/plugin/Plugin.hh) doesn't yet have an accessor for the name. It should be easy to add it.

**Comment by scpeters** [comment]
closed by #29
