### ISSUE TITLE
missing license file

### ISSUE THREAD

**Issue by ggulgulia** [ignitionrobotics/ign-plugin#71]
## Description

Is this repository missing a License file ? Most of the ignition packages have a License file but I can't find one here

**Comment by ggulgulia** [comment]
PR created: https://github.com/ggulgulia/ign-plugin/pull/1

**Comment by traversaro** [comment]
I think https://github.com/ignitionrobotics/ign-plugin/blob/ign-plugin1/COPYING can be used as license file for packaging, not sure why this repo is different anyhow.

**Comment by ggulgulia** [comment]
will be good it have a license file since I'm adding conan-recipes for ignition packages on official conan center index, also known as CCI ([see my PR's ](https://github.com/conan-io/conan-center-index/pulls/ggulgulia)both open and merged) and most of ignition repos have a LICENSE file which needs to be copied to a license directory as  per the standards of CCI. 

ign-plugin conan repo fails pre-build checks due to missing license file. I can use the file you mentioned but it will be easy to maintiain the conan recipes if they have uniform structure
